# config/model/lgbm.yaml
name: "LightGBM"
_target_: "lightgbm.LGBMRegressor"
# ハイパーパラメータ以外でモデル構造に依存する設定
use_gpu: true
# 前処理クラスのパスを記述（後述のスクリプトで動的ロード）
preprocessor_target: "src.preprocess.preprocess_lgbm.LGBMPreprocessor"
model_target: "src.models.lgbm_wrapper.LGBMWrapper"
# このモデルが必要とするデータ種別（data/フォルダの設定と紐付け）
data_category: "tabular"
n_ensembles: 5
sampling_interval: 5