# config/hparams/lgbm_default.yaml
objective: "binary"
metric: "auc"
boosting_type: "gbdt"
n_jobs: -1
random_state: 42
learning_rate: 0.084
num_leaves: 36
max_depth: 14
min_child_samples: 42
subsample: 0.635
colsample_bytree: 0.986
reg_alpha: 6.423
reg_lambda: 9.948
is_unbalance: true
use_time_decay: true
bagging_freq: 6
verbose: 1